### PR TITLE
remove_all_filters

### PR DESCRIPTION
**Pull request by MikePodgorniy**
remove_all_filters: "Прибрати всі фільтри",

### CODE REVIEW

**Comment by koresar** [comment]
Mate, would you like to take over this project? I'd happily grant you all access necessary s that you can merge and publish the rpm module.

**Comment by koresar** [comment]
v2.5.0 was just published.

**Comment by MikePodgorniy** [comment]
> Mate, would you like to take over this project? I'd happily grant you all access necessary s that you can merge and publish the rpm module.

ok! many thanks

**Comment by koresar** [comment]
@MikePodgorniy I would need your NPM username to grant you the publishing access.

**Comment by MikePodgorniy** [comment]
@koresar mike_podgorniy
https://www.npmjs.com/~mike_podgorniy

**Comment by koresar** [comment]
See nom invite in the email.

**Pull request merged**
